services:

  devcontainer:
    image: ghcr.io/ap-mdi-it/ml-courses:latest
    pull_policy: missing
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/

volumes:
  command-history-volume:
